# Generated by Django 4.1.4 on 2023-12-15 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradersApp', '0003_rename_category_units_property'),
    ]

    operations = [
        migrations.AddField(
            model_name='properties',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
