# Generated by Django 4.1.4 on 2023-12-15 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradersApp', '0004_properties_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental_information',
            name='agreemented_date',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
