# Generated by Django 4.1.4 on 2023-12-15 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradersApp', '0005_rental_information_agreemented_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental_information',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
