# Generated by Django 4.1.4 on 2023-12-15 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tradersApp', '0007_alter_rental_information_rent_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='properties',
            name='assigned_tenant',
        ),
        migrations.AddField(
            model_name='units',
            name='assigned_tenant',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='tradersApp.tenants'),
        ),
    ]
